# Generated by Django 6.1 on 2026-08-24 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('launches', '0003_alter_launchproject_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('requested_extensions', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_searches', to='brands.brandidea')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_searches', to='launches.launchproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=32)),
                ('available', models.BooleanField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('TAKEN', 'Taken'), ('UNKNOWN', 'Unknown'), ('CHECK_FAILED', 'Check failed')], max_length=20)),
                ('provider', models.CharField(max_length=100)),
                ('checked_at', models.DateTimeField()),
                ('raw_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_results', to='launches.launchproject')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='domains.domainsearch')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='domainsearch',
            index=models.Index(fields=['project', 'created_at'], name='ds_project_created_idx'),
        ),
        migrations.AddIndex(
            model_name='domainsearch',
            index=models.Index(fields=['project', 'status'], name='ds_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='domainsearch',
            index=models.Index(fields=['brand_idea', 'created_at'], name='ds_brand_created_idx'),
        ),
        migrations.AddIndex(
            model_name='domainresult',
            index=models.Index(fields=['project', 'domain'], name='dr_project_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='domainresult',
            index=models.Index(fields=['search', 'domain'], name='dr_search_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='domainresult',
            index=models.Index(fields=['project', 'available'], name='dr_project_avail_idx'),
        ),
        migrations.AddIndex(
            model_name='domainresult',
            index=models.Index(fields=['domain', 'checked_at'], name='dr_domain_checked_idx'),
        ),
        migrations.AddIndex(
            model_name='domainresult',
            index=models.Index(fields=['project', 'extension'], name='dr_project_ext_idx'),
        ),
        migrations.AddConstraint(
            model_name='domainresult',
            constraint=models.UniqueConstraint(fields=('search', 'domain'), name='uniq_search_domain'),
        ),
    ]
