# Generated by Django 6.1 on 2026-08-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_domainresult_registration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainresult',
            name='privacy_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainresult',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
