# Generated by Django 6.1 on 2026-08-23 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Internal project name.', max_length=255)),
                ('business_description', models.TextField(help_text='Description of the business.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating_brands', 'Generating Brands'), ('brands_ready', 'Brands Ready'), ('checking_domains', 'Checking Domains'), ('domain_selected', 'Domain Selected'), ('configuring_dns', 'Configuring DNS'), ('verifying_dns', 'Verifying DNS'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', help_text='Current workflow status.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Project owner.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='launch_user_created_idx'), models.Index(fields=['user', 'status'], name='launch_user_status_idx'), models.Index(fields=['updated_at'], name='launch_updated_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='launchproject_name_not_empty'), models.CheckConstraint(condition=models.Q(('business_description', ''), _negated=True), name='launchproject_description_not_empty')],
            },
        ),
    ]
