# Generated by Django 6.1 on 2026-08-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('launches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchproject',
            name='selected_brand',
            field=models.ForeignKey(blank=True, help_text='Selected brand idea, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_projects', to='brands.brandidea'),
        ),
    ]
