# Generated by Django 6.1 on 2026-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0002_launchproject_selected_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchproject',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATING_BRANDS', 'Generating Brands'), ('BRANDS_READY', 'Brands Ready'), ('CHECKING_DOMAINS', 'Checking Domains'), ('DOMAIN_SELECTED', 'Domain Selected'), ('CONFIGURING_DNS', 'Configuring DNS'), ('VERIFYING_DNS', 'Verifying DNS'), ('READY', 'Ready'), ('failed', 'Failed')], default='DRAFT', help_text='Current workflow status.', max_length=32),
        ),
    ]
