# Generated by Django 6.1 on 2026-08-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
        ('launches', '0003_alter_launchproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchproject',
            name='selected_domain',
            field=models.ForeignKey(blank=True, help_text='Selected domain, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_projects', to='domains.domainresult'),
        ),
    ]
