import uuid

from django.db import models

from domain_launch_assistant.launches.models import LaunchProject


class BrandIdea(models.Model):
    """
    Represents a brand name generated by Gemini for a launch project.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    project = models.ForeignKey(
        LaunchProject,
        on_delete=models.CASCADE,
        related_name="brand_ideas",
    )

    name = models.CharField(
        max_length=255,
    )

    description = models.TextField()

    generation_id = models.CharField(
        max_length=255,
        null=True,
        blank=True,
    )

    is_selected = models.BooleanField(
        default=False,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        constraints = [
            # A project can have at most one selected brand.
            models.UniqueConstraint(
                fields=["project"],
                condition=models.Q(is_selected=True),
                name="unique_selected_brand_per_project",
            ),

            # Brand names must be unique within a project,
            # ignoring capitalization.
            models.UniqueConstraint(
                models.functions.Lower("name"),
                "project",
                name="unique_brand_name_per_project_ci",
            ),

            # Name cannot be empty.
            models.CheckConstraint(
                condition=~models.Q(name=""),
                name="brandidea_name_not_empty",
            ),

            # Description cannot be empty.
            models.CheckConstraint(
                condition=~models.Q(description=""),
                name="brandidea_description_not_empty",
            ),
        ]

        indexes = [
            models.Index(
                fields=["project", "created_at"],
                name="brand_project_created_idx",
            ),
            models.Index(
                fields=["project", "is_selected"],
                name="brand_project_selected_idx",
            ),
            models.Index(
                fields=["project", "name"],
                name="brand_project_name_idx",
            ),
        ]

    def __str__(self):
        return self.name