"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

SECRET_KEY = config("DJANGO_SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config(
    "DJANGO_ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=lambda v: [h.strip() for h in v.split(",") if h.strip()],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",

    # local apps
    "domain_launch_assistant.users.apps.UsersConfig",
    "domain_launch_assistant.accounts.apps.AccountsConfig",
    "domain_launch_assistant.launches.apps.LaunchesConfig",
    "domain_launch_assistant.brands.apps.BrandsConfig",
    "domain_launch_assistant.domains.apps.DomainsConfig",
    "domain_launch_assistant.dns.apps.DnsConfig",
    "domain_launch_assistant.tasks.apps.TasksConfig",

]

# NOTE: CorsMiddleware must sit as high as possible, definitely before
# CommonMiddleware. There was a duplicated block here before (Security,
# Session, Common, Csrf, Auth, Messages, Clickjacking all appeared twice) —
# removed the duplicates and kept a single, correctly ordered list.
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(config("DATABASE_URL"))
}


# Custom user model
# Must be set before the first migration is ever run.
AUTH_USER_MODEL = "users.User" 


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Django REST Framework Settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "EXCEPTION_HANDLER": "domain_launch_assistant.utils.exceptions.custom_exception_handler",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# Simple JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


# CORS
# Adjust to match wherever the React dev server actually runs.

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:5173",
    cast=lambda v: [o.strip() for o in v.split(",") if o.strip()],
)


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}

# Redis (used for caching / Celery broker in later steps)

REDIS_URL = config("REDIS_URL")

GEMINI_API_KEY = config("GEMINI_API_KEY")
GEMINI_MODEL = config("GEMINI_MODEL")

BRAND_GENERATION_DEFAULT_COUNT = config("BRAND_GENERATION_DEFAULT_COUNT", default=5, cast=int)


NAMECOM_USERNAME = config("NAMECOM_USERNAME")
NAMECOM_API_TOKEN = config("NAMECOM_API_TOKEN")
NAMECOM_BASE_URL = config("NAMECOM_BASE_URL", default="https://api.name.com/core/v1")
NAMECOM_MAX_RETRIES = config("NAMECOM_MAX_RETRIES", default=3, cast=int)
NAMECOM_RETRY_BACKOFF_BASE = config("NAMECOM_RETRY_BACKOFF_BASE", default=0.5, cast=float)
DOMAIN_FRESHNESS_THRESHOLD_SECONDS = config(
    "DOMAIN_FRESHNESS_THRESHOLD_SECONDS", default=300, cast=int
)

# --- Simulate Registration (sandbox-only) — architecture.md section 19 ---
# A completely separate credential pair from NAMECOM_USERNAME/NAMECOM_API_TOKEN
# above, so a "sandbox" call can never accidentally be wired to production.
# No default for username/token: these are real credentials and the app
# should fail to boot without them, same discipline as NAMECOM_USERNAME.
NAMECOM_TEST_USERNAME = config("NAMECOM_TEST_USERNAME")
NAMECOM_TEST_API_TOKEN = config("NAMECOM_TEST_API_TOKEN")
NAMECOM_TEST_BASE_URL = config(
    "NAMECOM_TEST_BASE_URL", default="https://api.dev.name.com/core/v1"
)
# The hostname NAMECOM_TEST_BASE_URL must resolve to. DomainRegistrationSimulationService
# refuses to construct a sandbox client at all if this doesn't match —
# see domains/services/registration_simulation.py.
NAMECOM_SANDBOX_HOST = "api.dev.name.com"

# Fixed demo registrant contact used ONLY for the sandbox Simulate
# Registration call. Not tied to any user, never persisted anywhere —
# fictional placeholder data used to satisfy name.com's Create Domain
# contact requirements in the sandbox environment. Safe to default (no
# real PII); override in .env for a different demo persona if desired.
NAMECOM_TEST_CONTACT_FIRST_NAME = config("NAMECOM_TEST_CONTACT_FIRST_NAME", default="Demo")
NAMECOM_TEST_CONTACT_LAST_NAME = config("NAMECOM_TEST_CONTACT_LAST_NAME", default="Registrant")
NAMECOM_TEST_CONTACT_ADDRESS1 = config(
    "NAMECOM_TEST_CONTACT_ADDRESS1", default="123 Demo Street"
)
NAMECOM_TEST_CONTACT_CITY = config("NAMECOM_TEST_CONTACT_CITY", default="Denver")
NAMECOM_TEST_CONTACT_STATE = config("NAMECOM_TEST_CONTACT_STATE", default="CO")
NAMECOM_TEST_CONTACT_ZIP = config("NAMECOM_TEST_CONTACT_ZIP", default="80202")
NAMECOM_TEST_CONTACT_COUNTRY = config("NAMECOM_TEST_CONTACT_COUNTRY", default="US")
NAMECOM_TEST_CONTACT_EMAIL = config(
    "NAMECOM_TEST_CONTACT_EMAIL", default="demo-registrant@example.com"
)
NAMECOM_TEST_CONTACT_PHONE = config("NAMECOM_TEST_CONTACT_PHONE", default="+13035555555")

# Celery
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE


# Google Sign-In
# The OAuth 2.0 Client ID from Google Cloud Console (Credentials > OAuth
# client ID > Web application). Used server-side to verify that an ID
# token presented to auth/google/ was actually issued for *this* app.
GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID")