# Generated by Django 6.1 on 2026-08-23 11:43

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('launches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('generation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_ideas', to='launches.launchproject')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'created_at'], name='brand_project_created_idx'), models.Index(fields=['project', 'is_selected'], name='brand_project_selected_idx'), models.Index(fields=['project', 'name'], name='brand_project_name_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('project',), name='unique_selected_brand_per_project'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('project'), name='unique_brand_name_per_project_ci'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='brandidea_name_not_empty'), models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='brandidea_description_not_empty')],
            },
        ),
    ]
