# Generated by Django 6.1 on 2026-08-24 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('launches', '0004_launchproject_selected_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('DNS_CONFIGURATION', 'DNS Configuration'), ('DNS_RESOLUTION', 'DNS Resolution'), ('DOMAIN_READINESS', 'Domain Readiness')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error')], default='PENDING', max_length=16)),
                ('record_type', models.CharField(blank=True, max_length=16, null=True)),
                ('record_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_value', models.TextField(blank=True, null=True)),
                ('actual_value', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='domains.domainresult')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_checks', to='launches.launchproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='dc_project_idx'), models.Index(fields=['domain_result'], name='dc_domain_result_idx'), models.Index(fields=['project', 'status'], name='dc_project_status_idx')],
            },
        ),
    ]
